spring.application.name=spring-boot-rest-prometheus
server.port=8080
netology.profile.dev=true
management.endpoints.web.exposure.include=info,health,prometheus
spring.main.allow-bean-definition-overriding=true